name: Go

on:
  push:
    branches: [ master ]
    tags:
        - v*

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

#     - name: Get dependencies
#       run: |
#         go get -v -t -d ./...
#         if [ -f Gopkg.toml ]; then
#             curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
#             dep ensure
#         fi

    - name: Build
      run: make build-lambda-function && mkdir release && mv lambda.zip release/lambda.zip

    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: novacloud-lambda-functions
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-central-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'release'      # optional: defaults to entire repository
        DEST_DIR: github.com/${GITHUB_REPOSITORY}/${GITHUB_REF##refs/*/}